# This file was generated by GoReleaser. DO NOT EDIT.
cask "engram" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "ff7e6a6fb3eb180b1263e39c8cd48e2eb0471797e0c38fd64d29156918e89ebd"
      url "https://github.com/ertugrulhaskan/engram/releases/download/v#{version}/engram_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "785de7f542f8c2436b80cf636a20847cbef21472063327e5c2b42ea531021250"
      url "https://github.com/ertugrulhaskan/engram/releases/download/v#{version}/engram_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c44907ad0e39ed7324359f0d37470309539ceb0e86a7c05b5706101ead49d8ed"
      url "https://github.com/ertugrulhaskan/engram/releases/download/v#{version}/engram_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c8866a2e13cf4cec724dd9d775fd01d3a9b95849dd1859ac4afb9e6df595c5b9"
      url "https://github.com/ertugrulhaskan/engram/releases/download/v#{version}/engram_#{version}_linux_arm64.tar.gz"
    end
  end

  name "engram"
  desc "Terminal UI for browsing, searching, and sharing your Claude Code memories"
  homepage "https://engram.im"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "engram"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/engram"]
    end
  end

  # No zap stanza required

end
