# This file was generated by GoReleaser. DO NOT EDIT.
cask "engram" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "35dff81a9f49d39f2d6c2bbb033f6969a69e99e27306bb2ab89c21afe4d4c20b"
      url "https://github.com/ertugrulhaskan/engram/releases/download/v#{version}/engram_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "73e590ce3a3fbb0e546d3c7dd6a7f585666481d11f4ebaaa86ae6fd6d3178944"
      url "https://github.com/ertugrulhaskan/engram/releases/download/v#{version}/engram_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1497263caa2284bef92ccb43cd963f7b4ee5dc4797f880c0e7f8cf1fdc3dd9a0"
      url "https://github.com/ertugrulhaskan/engram/releases/download/v#{version}/engram_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9303286dee2aafdcb0893b5cc26a4da43fa57517e1374a8e8bad611a7bab344e"
      url "https://github.com/ertugrulhaskan/engram/releases/download/v#{version}/engram_#{version}_linux_arm64.tar.gz"
    end
  end

  name "engram"
  desc "Terminal UI for browsing, searching, and sharing your Claude Code memories"
  homepage "https://engram.im"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "engram"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/engram"]
    end
  end

  # No zap stanza required

end
